source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise'
gem 'activeadmin', '1.0.0.pre1'
gem 'ckeditor', github: 'galetahub/ckeditor'
gem 'paperclip'
gem 'grape', '~> 0.13.0'
gem 'grape-entity', '~> 0.4.8'
gem 'grape-swagger-rails', '~> 0.1.0'
