development:
  access_key_id: 'AKIAJFSIM3J3AJWZRXVA'
  secret_access_key: '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'
  s3_host_name: "s3-eu-central-1.amazonaws.com"

production:
  access_key_id: 'AKIAJFSIM3J3AJWZRXVA'
  secret_access_key: '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'
  s3_host_name: "s3-eu-central-1.amazonaws.com"