default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5

development:
  <<: *default
  database: <%= ENV['app_name'] %>_development
test:
  <<: *default
  database: <%= ENV['app_name'] %>_test
production:
  <<: *default
  database: 'd2lkra6b0cqdu7'
  host: 'ec2-54-228-183-183.eu-west-1.compute.amazonaws.com'
  username: 'rrgymarcmnrstk'
  password: 'ywC0VmuvfjTNcCwx991Bj9E-ld'
