default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5

development:
  <<: *default
  database: <%= ENV['app_name'] %>_development
test:
  <<: *default
  database: <%= ENV['app_name'] %>_test
production:
  <<: *default
  database: 'dffqtta7a54qlg'
  host: 'ec2-54-227-250-148.compute-1.amazonaws.com'
  username: 'tmihbjdlteeuuo'
  password: 'om3yodMD1JvTEL1yWCZAe78e4_'
