default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5
  username: 'postgres'
  password: '1111'


development:
  <<: *default
  database: teamdrive_development
test:
  <<: *default
  database: teamdrive_test
production:
  <<: *default
  
